### PR TITLE
admin/make-script-for-downloading-test-resource-use-cache

### PR DESCRIPTION
**Pull request by sir-sigurd**
**Pull request recommendations:**
- [x] Name your pull request _your-development-type/short-description_. Ex: _feature/read-tiff-files_
- [x] Link to any relevant issue in the PR description. Ex: _Resolves [gh-12], adds tiff file format support_

related to https://github.com/AllenCellModeling/napari-aicsimageio/issues/23
- [x] Provide context of changes.

Makes script for downloading use [`install()`](https://docs.quiltdata.com/api-reference/package#Package.install) instead of [`fetch()`](https://docs.quiltdata.com/api-reference/package#Package.fetch). `install()` uses cache so already downloaded files won't be re-downloaded in case of re-running script after network failure.

- [ ] Provide relevant tests for your feature or bug fix.
- [ ] Provide or update documentation for any feature added by your pull request.

Thanks for contributing!

### CODE REVIEW

**Review by JacksonMaxfield — APPROVED** [review]
Ahhhh thats a nice and easy change. Thanks!

**Comment by JacksonMaxfield** [comment]
Errrrr hm. I'm not sure I like the cache for the biggest reason of:

"lets say i am a new contributor for the first time. when i download the test resources, make my PR and then delete the repo locally, i still have 3GB of cached data on disk somewhere"

**Comment by sir-sigurd** [comment]
> Is that accurate?

Package data is only stored in directory specified by the `dest` parameter. The only data stored outside of this directory consists of previously downloaded manifests and data **about** previously downloaded package data files.

**Comment by JacksonMaxfield** [comment]
Perfect. Thanks for the info.

**Pull request merged**
