### PR TITLE
feature/initial-release

### PR DESCRIPTION
**Pull request by JacksonMaxfield**
**Pull request recommendations:**
- [x] Name your pull request _your-development-type/short-description_. Ex: _feature/read-tiff-files_
- [x] Link to any relevant issue in the PR description. Ex: _Resolves [gh-12], adds tiff file format support_
- [x] Provide context of changes.

[napari](https://github.com/napari) has added custom plugins! Their team is cool, napari is cool, it would be nice to have a plugin for the library. It was pretty easy to setup [after some initial confusions](https://github.com/napari/cookiecutter-napari-plugin/issues/4).

There are two plugin options:
* `aicsimageio`
* `aicsimageio_delayed`

There are some details available on why each one is there available on the README changes of this PR.

By default the image channels are turned off so that initial load is fast after the data has loaded (and because seeing 4+ channels at a time can be difficult to comprehend what is going on in the image)

- [x] Provide relevant tests for your feature or bug fix.

All tests pass except for the fact that there are known file formats that don't work until future patches because their readers are missing the `get_channel_names` function. See [aicsimageio-88](https://github.com/AllenCellModeling/aicsimageio/pull/88).

Once that PR is merged and a version is released I will bump the `aicsimageio` dep version to `3.1.4`.

- [x] Provide or update documentation for any feature added by your pull request.

**To test this out:**
```bash
git clone git@github.com:AllenCellModeling/napari-aicsimageio.git
git checkout feature/napari-plugin
pip install -e .
pip install git+https://github.com/napari/napari.git
napari
```

Then load a file from the UI.

**Potential future additions:**
From my understanding, the ["labels" layer](https://github.com/napari/napari/blob/master/napari/layers/labels/labels.py#L16) is something we could _heavily_ utilize. From initial thinking, we could check channel names for `_seg`, or `segmentation` and then assume those channels go on the labels layer. Just a thought, feedback appreciated.

Thanks for contributing!

### CODE REVIEW

**Comment by JacksonMaxfield** [comment]
>     1. Why provide both delayed and non-delayed flavors? If you only provided the delayed form, wouldn't that satisfy all users?

It would satisfy all users but if the user _can_ fit the image into memory then the actual experience of using napari is drastically improved when they click the like "play through dimension" button. Its 2ms delay vs network delay.

>     2. Is there a way to strip out all the unneeded extra dependencies?

You mean the "dev" dependencies? Those are there for testings and development. Pretty minimal imo.

>     3. I'm not sure the tests are really adding value over the aicsimageio tests, but I suppose any tests are better than no tests...  To me a better test would be: does it integrate into napari?  (Does napari maybe have suggestions for unit testing plugins?)

I think there is value in having tests which is basically are we consistent with their API, specifically the `List[ArrayLike, Dict]` object and `Callable` return from the two functions. [Here](https://github.com/napari/cookiecutter-napari-plugin/blob/master/napari-%7B%7Bcookiecutter.plugin_name%7D%7D/tests/test_%7B%7Bcookiecutter.module_name%7D%7D.py) is there example tests.

**Comment by toloudis** [comment]
> > ```
> > 1. Why provide both delayed and non-delayed flavors? If you only provided the delayed form, wouldn't that satisfy all users?
> > ```
> 
> It would satisfy all users but if the user _can_ fit the image into memory then the actual experience of using napari is drastically improved when they click the like "play through dimension" button. Its 2ms delay vs network delay.
> 

How does a user select which of the two plugins to invoke? (Is that documented?)  My only concern is putting extra responsibility on the users to figure things out.

**Comment by toloudis** [comment]
> > ```
> > 3. I'm not sure the tests are really adding value over the aicsimageio tests, but I suppose any tests are better than no tests...  To me a better test would be: does it integrate into napari?  (Does napari maybe have suggestions for unit testing plugins?)
> > ```
> 
> I think there is value in having tests which is basically are we consistent with their API, specifically the `List[ArrayLike, Dict]` object and `Callable` return from the two functions. [Here](https://github.com/napari/cookiecutter-napari-plugin/blob/master/napari-%7B%7Bcookiecutter.plugin_name%7D%7D/tests/test_%7B%7Bcookiecutter.module_name%7D%7D.py) is there example tests.

My point here was that your tests don't really need to open all those different file types. They just need to do it with one.  The aicsimageio tests cover the rest of it.  And I like the example tests that napari shows in their cookiecutter :)

**Comment by JacksonMaxfield** [comment]
> How does a user select which of the two plugins to invoke? (Is that documented?) My only concern is putting extra responsibility on the users to figure things out.

In an upcoming PR to napari there will be a [plugin sorter](https://github.com/napari/napari/pull/1023#issuecomment-599135148)

**Comment by JacksonMaxfield** [comment]
> Thanks for figuring this out. The code is clean and elegant. I don't really have any comments on that level having looked through it all. My one comment would be on the delayed vs in-memory versions of the reader. Would it be possible to combine them and have the module determine which one to load based on resources and the file that was pointed to?

Possible but I don't really want to touch that right now tbh. Maybe in `0.2.0`

**Pull request merged**
