### PR TITLE
admin/update-min-aicsimageio-ver-and-move-to-gpl3

### LINKED ISSUE #35: Discussion: license changes
I am opening this issue to have centralized discussion over the two options that are available for this package for handling upstream license changes.

1. `napari-aicsimageio` only supports non-GPL open access licensed readers. I.e. TIFF, PNG, GIF, Zarr, ND2, DV, etc. and `napari-aicsimageio` is able to stay `BSD-3`
2. `napari-aicsimageio` continues to install all formats (including bioformats, lif, etc.) and we change the license to GPL.

I guess there is a third option where we do both and we release `napari-aicsimageio` under BSD and `napari-aicsimageio-gpl` under GPL.

Thoughts? @tlambert03 @psobolewskiPhD

### PR DESCRIPTION
**Pull request by JacksonMaxfield**
**Pull request recommendations:**
- [x] Name your pull request _your-development-type/short-description_. Ex: _feature/read-tiff-files_
- [x] Link to any relevant issue in the PR description. Ex: _Resolves [gh-12], adds tiff file format support_

Resolves #35 

- [x] Provide context of changes.

Sets the new license to GPL because we are upgrading to aicsimageio v4.4.0 and installing all optional reader deps.
Additionally fixes and updates some general README info.

- [ ] Provide relevant tests for your feature or bug fix.
- [x] Provide or update documentation for any feature added by your pull request.

Tagging @psobolewskiPhD @tlambert03. Any thoughts?

Thanks for contributing!

### CODE REVIEW

**Comment by JacksonMaxfield** [comment]
Ignoring the failing builds. Will rerun when 4.4.0 is actually pushed to pypi

**Comment by psobolewskiPhD** [comment]
OK, so this is sort of insane, but it works...
What if, the error from napari-aicsimageio when LIF or CZI is tried, but the extras are not installed (in other words, the default install, without the GPL parts) told the use to open the console and do:
`%pip install readlif`
or 
`%pip install aicspylibczi`
(this is from: https://github.com/ipython/ipython/pull/11524)
It works! You don't even need to relaunch napari! You can see console output and the scene selector of a LIF.
image

**Comment by JacksonMaxfield** [comment]
> OK, so this is sort of insane, but it works... What if, the error from napari-aicsimageio when LIF or CZI is tried, but the extras are not installed (in other words, the default install, without the GPL parts) told the use to open the console and do: `%pip install readlif` or `%pip install aicspylibczi` (this is from: [ipython/ipython#11524](https://github.com/ipython/ipython/pull/11524)) It works! You don't even need to relaunch napari! You can see console output and the scene selector of a LIF. image
> 
> Edit: here's `pip show` from the terminal, showing that it installed in the right env.
> 
> ```
> ─ ~/dev ······················································· ✔  3m 44s ─╮
> ╰─ pip show readlif                                               (napari-CL) ─╯
> Name: readlif
> Version: 0.6.5
> Summary: Fast Leica LIF file reader written in python
> Home-page: https://github.com/nimne/readlif
> Author: Nick Negretti
> Author-email: nick.negretti@gmail.com
> License: GPLv3
> Location: /Users/piotrsobolewski/Dev/miniforge3/envs/napari-CL/lib/python3.9/site-packages
> Requires: Pillow
> Required-by: 
> ```

Uhhhhhh can you make a PR for that?

**Comment by JacksonMaxfield** [comment]
Errr wait, this PR is adding all the installs. No reason to add that once this is merged and deployed

**Comment by JacksonMaxfield** [comment]
I have no idea why the tests are failing on Windows... but I am going to ship this and release so that it unblocks a lot of people.

Will make an issue for fixing windows tests.

**Comment by JacksonMaxfield** [comment]
@psobolewskiPhD release is out v0.5.0.

If you have a chance, can you make a fresh env and let me know if everything installs and runs correctly.

I am technically out of town this week so will be sporadic in response but hopefully everything works for you!

**Comment by psobolewskiPhD** [comment]
Everything is golden!
Works perfectly, both readlif and aicspylibczi.

**Pull request merged**
